service: google-spreadsheet-to-s3

package:
  patterns:
    - "!.github/workflows/**"
    - "!.gitignore"
    - "!assets/**"
    - "!LICENSE"
    - "!README.md"
    - "!terraform/**"

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.10
  stage: ${opt:stage, 'dev'}
  region: eu-west-3
  deploymentBucket: sls-deployment-bucket-${env:CI_ENV}
  environment:
    BUCKET_NAME: ${env:BUCKET_NAME}
    BUCKET_KEY: ${env:BUCKET_KEY}
    LOG_LEVEL: INFO
    SPREADSHEET_ID: ${env:SPREADSHEET_ID}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        - "arn:aws:s3:::riblup-home-management/*"

functions:
  run:
    handler: handler.run
    description: Downloads specific Google Spreadsheet and loads into S3.
    timeout: 60
    events:
      - schedule:
          rate: cron(0 1 * * ? *)
          name: google-spreadsheet-to-s3-sched
