service: google-spreadsheet-to-s3

plugins:
  - serverless-python-requirements
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 3

provider:
  name: aws
  runtime: python3.12
  stage: ${opt:stage, 'dev'}
  region: eu-west-3
  deploymentBucket:
    name: sls-deployments-${aws:accountId}-${self:provider.region}
    maxPreviousDeploymentArtifacts: 1
  environment:
    BUCKET_NAME: ${env:BUCKET_NAME}
    BUCKET_KEY: ${env:BUCKET_KEY}
    LOG_LEVEL: INFO
    SPREADSHEET_ID: ${env:SPREADSHEET_ID}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        - "arn:aws:s3:::riblup-home-management/*"

functions:
  run:
    handler: handler.run
    description: Downloads specific Google Spreadsheet and loads into S3.
    timeout: 60
    events:
      - schedule:
          rate: cron(0 1 * * ? *) # 1:00 am UTC time
          name: ${self:service}-sched
