name: Serverless Deploy

on:
  push:
    branches:
      - main

jobs:
  sls-deploy:
    name: Serverless Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/serverless/
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Create JSON
        id: create-json
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: "service-account-credentials.json"
          json: ${{ secrets.SERVICE_ACCOUNT_CREDENTIALS }}
          dir: "serverless/"

      - name: Deploy created JSON
        run: |
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git add .
          git add --force service-account-credentials.json
          git status
          git commit -a -m "Deploy Service Account Credentials JSON"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm shrinkwrap

      - run: npm ci

      - name: serverless install plugins
        uses: serverless/github-action@v4
        with:
          args: |
            -c "
            cd ./serverless &&
            serverless plugin install --name serverless-python-requirements &&
            serverless plugin install --name serverless-prune-plugin
            "
          entrypoint: /bin/sh

      - name: serverless deploy
        uses: serverless/github-action@v4
        with:
          args: -c "cd ./serverless && serverless deploy --stage ${{ env.CI_ENV }} --verbose"
          entrypoint: /bin/sh
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          BUCKET_NAME: ${{ vars.BUCKET_NAME }}
          BUCKET_KEY: ${{ vars.BUCKET_KEY }}
          SPREADSHEET_ID: ${{ vars.SPREADSHEET_ID }}
